out_dir: results
tb: no
use_cuda: yes
gpus: [0,1,2,3] # [0,1,2,3]
save_best: yes
save_all: no

no_epochs: &epochs 150

dataset_root: /raid/workspace/alexandrug/coco/coco
train_image_set: train2017
val_image_set: val2017

no_classes: 80
data_mean: &data_mean [0.485, 0.456, 0.406]
data_std: &data_std [0.229, 0.224, 0.225]
in_sizes: [256, 128, 64, 32]
max_expand: 1.2

batch_size: 64  # 96
num_workers: 30

model:
  name: ResNetUNet

train:
  name: TrainDefault
  batch_log_freq: 10
  algorithm: SGD
  algorithm_args:
    lr: &lr 0.01
    momentum: 0.9
    weight_decay: 0.0005
  lr_scheduler:
    use: yes
    mode: "step"
    lr: *lr
    epochs: *epochs
    lr_step: 40
    warmup_epochs: 2
  data_mean: *data_mean
  data_std: *data_std

#  lr_scheduler:
#    use: yes
#    mode: "none"
#    lr: *lr
#    epochs: *epochs
#    warmup_epochs: 1
#  data_mean: *data_mean
#  data_std: *data_std
#

log_key: []