out_dir: results
tb: no
use_cuda: yes
save_best: yes
save_all: no

no_epochs: 120

dataset_root: /media/andrei/Samsung_T51/coco
train_image_set: val2017 # train2017
val_image_set: val2017

no_classes: 80
data_mean: [0.485, 0.456, 0.406]
data_std: [0.229, 0.224, 0.225]
in_sizes: [32] #[256, 128, 64, 32]
max_expand: 2.

batch_size: 1
num_workers: 8

model:
  name: ResNetUNet

train:
  name: TrainDefault
  batch_log_freq: 5
  algorithm: RMSprop
  algorithm_args:
    lr: 0.0001

log_key: []