out_dir: results
tb: no
use_cuda: yes
save_best: yes
save_all: no

no_epochs: 120

dataset_root: /raid/workspace/alexandrug/coco/coco
train_image_set: train2017 # train2017
val_image_set: val2017

no_classes: 80
data_mean: [0.485, 0.456, 0.406]
data_std: [0.229, 0.224, 0.225]
in_sizes: [256, 128, 64, 32]
max_expand: 2.

batch_size: 32
num_workers: 40

model:
  name: ResNetUNet

train:
  name: TrainDefault
  batch_log_freq: 10
  algorithm: RMSprop
  algorithm_args:
    lr: 0.0003

log_key: []